:mod:`pyre.filesystem.exceptions`
=================================

.. py:module:: pyre.filesystem.exceptions

.. autoapi-nested-parse::

   Definitions for all the exceptions raised by this package



Module Contents
---------------

.. py:exception:: GenericError(uri, **kwds)

   Bases: :class:`pyre.framework.exceptions.FrameworkError`

   Base class for all errors in this package

   Can be used as a catchall when detecting errors generated by this package


.. py:exception:: DirectoryListingError(error, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.GenericError`

   Exception raised when something goes wrong with listing the contents of a local directory

   .. attribute:: description
      :annotation: = error while accessing '{0.uri}': {0.error}

      


.. py:exception:: MountPointError(error, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.GenericError`

   Exception generated when the root of a filesystem is invalid

   .. attribute:: description
      :annotation: = error while mounting '{0.uri}': {0.error}

      


.. py:exception:: FilesystemError(filesystem, node, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.GenericError`

   Base class for all filesystem errors

   Can be used as a catchall when detecting filesystem related exceptions


.. py:exception:: NotFoundError(fragment, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when attempting to find a node and the supplied URI does not exist

   .. attribute:: description
      :annotation: = while looking for {0.rep!r}: {0.fragment!r} not found

      


.. py:exception:: SourceNotFoundError

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when attempting to find a node and the supplied URI does not exist

   .. attribute:: description
      :annotation: = while looking for {0.rep!r}: file not found

      


.. py:exception:: FolderError(fragment, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when a request is made for the contents of a node that is not a folder

   .. attribute:: description
      :annotation: = while looking for {0.rep!r}: {0.fragment!r} is not a folder

      


.. py:exception:: IsFolderError

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when a request is made to open a folder

   .. attribute:: description
      :annotation: = while opening {0.rep!r}: can't open; it is a folder

      


.. py:exception:: FolderInsertionError(target, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when attempting to insert a node in a filsystem and the target node is not
   a folder

   .. attribute:: description
      :annotation: = error while inserting {0.rep!r}: {0.target!r} is not a folder

      


.. py:exception:: NotRootError

   Bases: :class:`pyre.filesystem.exceptions.FilesystemError`

   Exception raised when attempting to insert a node with an absolute uri at a location other
   than the root of the filesystem a folder

   .. attribute:: description
      :annotation: = cannot insert absolute path {0.rep!r} in node {0.target!r}

      


.. py:exception:: URISpecificationError(reason, **kwds)

   Bases: :class:`pyre.filesystem.exceptions.GenericError`

   Exception raised when the supplied uri cannot be decoded

   .. attribute:: description
      :annotation: = {0.rep!r}: {0.reason}

      


